#!/bin/bash -eux

die() { echo "$@" >&2; exit 1; }

# What TI says
packages='
  git-core gnupg flex bison gperf build-essential
  zip curl libc6-dev libncurses5-dev:i386 x11proto-core-dev
  libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386
  libgl1-mesa-dev g++-multilib mingw32 openjdk-6-jdk tofrodos
  python-markdown libxml2-utils xsltproc zlib1g-dev:i386
'

# Other stuff
packages+=' ccache uboot-mkimage'

sudo apt-get install -y -q $packages | grep -v newest > /dev/null

if [ ! -f /usr/lib/i386-linux-gnu/libGL.so ]; then
  sudo ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/i386-linux-gnu/libGL.so
fi

[ $(readlink -f /usr/lib/i386-linux-gnu/mesa/libGL.so.1) = $(readlink -f /usr/lib/i386-linux-gnu/libGL.so) ] || die "libGL.so.1 isn't the same as libGL.so"
